title: Manoa Xchange
description: A place to buy and sell at UHM
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: true
  repository_url: #
social:
  type: Organization
gems:
  - jekyll-mentions